// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageMode } from "./ImageMode";

export type ImageInfo<T> = { id: string, parent_id: string | null, params: T, mode: ImageMode, };
