// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenParams } from "./OpenParams";
import type { RotateParams } from "./RotateParams";
import type { SaveParams } from "./SaveParams";
import type { SplitParams } from "./SplitParams";
import type { StageData } from "./StageData";

export type ProcessingStage = { "type": "open" } & StageData<OpenParams> | { "type": "rotate" } & StageData<RotateParams> | { "type": "split" } & StageData<SplitParams> | { "type": "save" } & StageData<SaveParams>;
