// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageInfo } from "./ImageInfo";

export type StageData<T> = { images: Array<ImageInfo<T>>, images_lookup: { [key in string]?: number }, current_image: string | null, };
