// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageInfo<T> = { id: string, parent_id: string | null, params: T, mode: ImageMode, };

export type ImageMode = "Auto" | "Manual" | "Skip";

export type OpenParams = { file_path: string, };

export type ProcessingStage = { "type": "open" } & StageData<OpenParams> | { "type": "rotate" } & StageData<RotateParams> | { "type": "split" } & StageData<SplitParams> | { "type": "save" } & StageData<SaveParams>;

export type RotateParams = { angle: number, };

export type SaveParams = Record<string, never>;

export type SplitParams = { x1: number, x2: number, };

export type StageData<T> = { images: Array<ImageInfo<T>>, images_lookup: { [key in string]?: number }, current_image: string | null, };
